### ISSUE TITLE
Test Scanning Options

### ISSUE THREAD

**Issue by ProfessorAkram** [cs-utulsa/VRSandbox#7]

**Comment by Ku-Bri** [comment]
### PROGRESS


### SLOWdowns


### RESOURCES

**Comment by Ku-Bri** [comment]
###PROGRESS
Working on refining the Matterport scanning process to produce better mesh results in the hopes that, the more clearly defined the items in the room are, the easier we might be able to automate the separation process of those items into separate objects. 

Looking at options for buying or building a mount that will work for spaces that require lower scans/scans up against the wall to get the detail for separation of objects from the wall. 

###SLOWDOWNS
Known issues: limits of the tripod - the legs limit how close to walls and other objects the camera can be placed and when the tripod is set as low as possible, the legs can be seen in the scans. Lowest scan possible with current tripod is the camera base at 14 1/8". 

Being able to view the scans in the Matterport system. 

###COMPLETED
Took 84 scans of Rayzor Hall 2055 with the Matterport. Scans 1-24 were taking at camera base height of 63 5/8", scans 25-50 were taken at camera base height of 35 3/8", and scans 51-84 were taken at camera base height of 14 1/8". The scan is still processing. Immediately known issues: the tripod limits how close to walls etc that we can scan, as well as how low with the lowest height being 14 1/8". Also, at the lowest height the tripod legs can be seen in the scan. 

###RESOURCES
Some links I used to get started with the Matterport:
https://matterport.com/matterport-academy
https://www.youtube.com/watch?v=VTvFVUZhm7Y
https://www.wegetaroundnetwork.com/topic/5495/10-scanning-tips-for-new-matterport-users/

###PROGRESS IMAGES

**Comment by 18dmontgomery** [comment]
## PROGRESS

During my research into Matterport scanning, I explored the various add-ons and features it offers. One of the first options I looked into was MatterPak, which provided a .obj file containing mesh objects. However, we encountered a challenge as there was no effective way to differentiate one object from another within the file. Consequently, this approach did not prove useful for our purposes.

Next, I delved into e57 files, which offered a more promising outcome. These files contained a significant amount of data, although sorting through it required considerable effort. While it provided a step forward, we continued to seek a solution that would better suit our needs.

Ultimately, I pursued the option of outsourcing BIM (Building Information Modeling) files to Matterport. This avenue yielded favorable results, providing us with a 3D representation of the space. However, it is important to note that the BIM files did not include textures.

## SLOWDOWNS

One of the significant considerations during this process is the time required for processing the BIM files. Typically, it takes approximately 2-4 business days to complete this task. It is essential to account for this timeline when planning projects involving BIM file conversion.

Moreover, it is crucial to consider the cost associated with outsourcing BIM files to Matterport. I reached out directly to Matterport and received the following price breakdown for furniture and architecture BIM files:

- 1 sqft - 1000 sqft: $245 - $680
- 1000 sqft - 5000 sqft: $750 - $1840
- 5000 sqft - 10000 sqft: $1750 - $2800
- 10000 sqft - 25000 sqft: $3500 - $5950
- 25000 sqft - 50000 sqft: $6800 - $12240

These costs provide a perspective on the financial implications associated with generating BIM files through outsourcing.

## COMPLETED

As part of my work, I successfully generated two BIM files—one for the North Campus and another for Dr. Gamble's office. These files now serve as 3D representations of the respective spaces.

## RESOURCES

For further information on the Scan to BIM process, the following resource from Matterport's support website provides valuable insights: [Scan to BIM - Matterport Support](https://support.matterport.com/s/article/Scan-to-BIM?language=en_US)

Certainly! Here's an example of how to add progress images:

### PROGRESS IMAGES



![Scan 1](https://github.com/cs-utulsa/VRSandbox/assets/17186668/7d2b015f-b8d4-4f7a-bf48-db804a4c786b)


![Scan 2](https://github.com/cs-utulsa/VRSandbox/assets/17186668/b849e097-d216-4d92-a55b-20320cf355a3)

**Comment by Ku-Bri** [comment]
### PROGRESS

Photogrammetry Exploration/Comparison Continued: 
I used the Ipad to take 1014 photos of Rayzor Hall 2055. I took photos at 3 different levels: approximately 7', 5'3", and 21". Using a computer in 2055, I imported the photos via cable and uploaded them to Reality Capture. I aligned the images 

### SLOWDOWNS

The process of taking the photos is tedious and took between 1.5 and 2 hours. The time for aligning images varies but took between 30 minutes and and an hour and crashed Reality Capture several times. 

### COMPLETED

Took photos for VR production by Reality Capture.

**Comment by Ku-Bri** [comment]
### PROGRESS

> Testing modified photogrammetry image capture. 
I am testing a new pattern of image capture to get a more detailed, complete, and accurate model. 

For the first set of images, I took of 2055 for photogrammetry within Reality Capture I used advise from Reality Capture and other sources and followed the contour of the walls to photograph the room. Using advise from Matterport and other sources I did this at 3 different levels. Then, at certain points that appeared to be junctions of large amounts of visual data, I captured images (facing out from that point) in a circle in that area.

For the second set of images, I am taking the photos facing the walls and following the contours of the walls and large objects where I will spend more time on denser areas in order to fill some of the holes/indistinct areas.

**Comment by Ku-Bri** [comment]
## PROGRESS
### Creating object separated models using the scan data as a reference: 
I am starting from the North Campus Matterport MatterPak download,  which includes a .obj and .mtl file, and opening that in Blender. I am using the single mesh model as a reference for creating an object separated model similar to the North Campus BIM model we purchased from Matterport. 

The goal is to record the time it takes to create a comparable model of North Campus to compare that to the time/money/manpower expense to that of the Matterport BIM model. 
In addition to the comparison itself, this is intended to be the basis of a submission to the IEEE DTPI 2023 conference (submission due July 27th). 

## SLOWDOWNS
Before the production comparison begins, I am researching how to effectively and efficiently create a similar quality model in Blender. To this end, I am looking at add-ons for Blender that enable CAD-like creation and editing as well as specific functions within Blender that will speed up the modeling process. 

## COMPLETED


## PROGRESS IMAGES

**Comment by ProfessorAkram** [comment]
#CLOSED: 
Research shows that scanned data will not yield the results we want. 
Moving forward we will develop room models referencing scanned data and CAD files. 
Progress continues to issue #13
